-- Generated from template

require('gamemode')

function Precache( context )

	PrecacheResource("model", "models/heroes/undying/undying_minion_torso.vmdl", context)

	PrecacheResource("particle", "particles/warning_aoe_ring.vpcf", context)
	PrecacheResource("particle", "particles/warning_aoe_ring_sticky.vpcf", context)
	PrecacheResource("particle", "particles/warning_green_aoe_ring_sticky.vpcf", context)

	PrecacheResource("particle", "particles/perks/greater_interval_absorbing_shield.vpcf", context)	

	PrecacheUnitByNameSync("npc_dota_hero_a_mighty_boar", context)
	PrecacheUnitByNameSync("npc_dota_hero_demonic_warrior", context)
	PrecacheUnitByNameSync("npc_dota_hero_scroll_collector", context)
	PrecacheUnitByNameSync("npc_dota_hero_ancient_siege_engine", context)
	PrecacheUnitByNameSync("npc_dota_hero_wind_harpy", context)
	PrecacheUnitByNameSync("npc_dota_hero_air_ship", context)
	PrecacheUnitByNameSync("npc_dota_hero_lunar_horse", context)

	PrecacheUnitByNameSync("npc_dota_hero_ferocious_lava_elemental", context)
	PrecacheUnitByNameSync("npc_dota_hero_iron_claw", context)
	PrecacheUnitByNameSync("npc_dota_hero_smodhex_satyr_warlock", context)
	PrecacheUnitByNameSync("npc_dota_hero_nether_drake", context)
	PrecacheUnitByNameSync("npc_dota_hero_drono_red_dragonkin_commander", context)
	PrecacheUnitByNameSync("npc_dota_hero_stikx_the_gentleman", context)
	PrecacheUnitByNameSync("npc_dota_hero_treasure_on_a_tree", context)
	PrecacheUnitByNameSync("npc_dota_hero_structures_of_xunra", context)
	PrecacheUnitByNameSync("npc_dota_hero_samurai_of_chaos", context)
	PrecacheUnitByNameSync("npc_dota_hero_elite_royal_guardian", context)

	PrecacheUnitByNameSync("npc_dota_hero_bhamuka_all_consuming_god", context)
	PrecacheUnitByNameSync("npc_dota_hero_the_curse_of_agony", context)
	PrecacheUnitByNameSync("npc_dota_hero_the_dungeoneer", context)
	PrecacheUnitByNameSync("npc_dota_hero_sinastra", context)
	PrecacheUnitByNameSync("npc_dota_hero_deathspeaker_xunra", context)

	PrecacheUnitByNameSync("npc_dota_hero_grimstroke", context)
	PrecacheUnitByNameSync("npc_dota_hero_juggernaut", context)
	PrecacheUnitByNameSync("npc_dota_hero_sven", context)
	PrecacheUnitByNameSync("npc_dota_hero_necrolyte", context)

	PrecacheResource("soundfile", "soundevents/game_sounds_custom.vsndevts", context)

	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_announcer.vsndevts", context)

	PrecacheResource("soundfile", "soundevents/game_sounds_roshan_halloween.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_items.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_creeps.vsndevts", context)

	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_huskar.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_spirit_breaker.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_pangolier.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_slardar.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_chaos_knight.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tiny.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_batrider.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_jakiro.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_dragon_knight.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lone_druid.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tidehunter.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_visage.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_beastmaster.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_chen.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_queenofpain.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_elder_titan.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_luna.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_pugna.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lich.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_bristleback.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_furion.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_troll_warlord.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_sandking.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_dark_willow.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_antimage.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_shredder.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_shadowshaman.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_bane.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_terrorblade.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_zuus.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_winter_wyvern.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_faceless_void.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_dazzle.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_grimstroke.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_kunkka.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts", context)
	
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_grimstroke.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_dark_seer.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_naga_siren.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_nevermore.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_outworld_destroyer.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_leshrac.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_bane.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_dazzle.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_troll_warlord.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_monkey_king.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_treant.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_winter_wyvern.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_juggernaut.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_sven.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/voscripts/game_sounds_vo_necrolyte.vsndevts", context)

end

function Activate()
	GameRules.GameMode = GameMode()
	GameRules.GameMode:_InitGameMode()

	--GameRules:GetGameModeEntity():SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_INTELLIGENCE_SPELL_AMP_PERCENT, 5.0)
end
